/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyNftsRouteImport } from './routes/my-nfts'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MintIndexRouteImport } from './routes/mint/index'
import { Route as MintCollectionRouteImport } from './routes/mint/collection'
import { Route as CollectionAddressRouteImport } from './routes/collection.$address'
import { Route as NftContractTokenIdRouteImport } from './routes/nft.$contract.$tokenId'

const MyNftsRoute = MyNftsRouteImport.update({
  id: '/my-nfts',
  path: '/my-nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MintIndexRoute = MintIndexRouteImport.update({
  id: '/mint/',
  path: '/mint/',
  getParentRoute: () => rootRouteImport,
} as any)
const MintCollectionRoute = MintCollectionRouteImport.update({
  id: '/mint/collection',
  path: '/mint/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionAddressRoute = CollectionAddressRouteImport.update({
  id: '/collection/$address',
  path: '/collection/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const NftContractTokenIdRoute = NftContractTokenIdRouteImport.update({
  id: '/nft/$contract/$tokenId',
  path: '/nft/$contract/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/marketplace': typeof MarketplaceRoute
  '/my-nfts': typeof MyNftsRoute
  '/collection/$address': typeof CollectionAddressRoute
  '/mint/collection': typeof MintCollectionRoute
  '/mint': typeof MintIndexRoute
  '/nft/$contract/$tokenId': typeof NftContractTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/marketplace': typeof MarketplaceRoute
  '/my-nfts': typeof MyNftsRoute
  '/collection/$address': typeof CollectionAddressRoute
  '/mint/collection': typeof MintCollectionRoute
  '/mint': typeof MintIndexRoute
  '/nft/$contract/$tokenId': typeof NftContractTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/marketplace': typeof MarketplaceRoute
  '/my-nfts': typeof MyNftsRoute
  '/collection/$address': typeof CollectionAddressRoute
  '/mint/collection': typeof MintCollectionRoute
  '/mint/': typeof MintIndexRoute
  '/nft/$contract/$tokenId': typeof NftContractTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/marketplace'
    | '/my-nfts'
    | '/collection/$address'
    | '/mint/collection'
    | '/mint'
    | '/nft/$contract/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/marketplace'
    | '/my-nfts'
    | '/collection/$address'
    | '/mint/collection'
    | '/mint'
    | '/nft/$contract/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/marketplace'
    | '/my-nfts'
    | '/collection/$address'
    | '/mint/collection'
    | '/mint/'
    | '/nft/$contract/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  MarketplaceRoute: typeof MarketplaceRoute
  MyNftsRoute: typeof MyNftsRoute
  CollectionAddressRoute: typeof CollectionAddressRoute
  MintCollectionRoute: typeof MintCollectionRoute
  MintIndexRoute: typeof MintIndexRoute
  NftContractTokenIdRoute: typeof NftContractTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-nfts': {
      id: '/my-nfts'
      path: '/my-nfts'
      fullPath: '/my-nfts'
      preLoaderRoute: typeof MyNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint/': {
      id: '/mint/'
      path: '/mint'
      fullPath: '/mint'
      preLoaderRoute: typeof MintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint/collection': {
      id: '/mint/collection'
      path: '/mint/collection'
      fullPath: '/mint/collection'
      preLoaderRoute: typeof MintCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$address': {
      id: '/collection/$address'
      path: '/collection/$address'
      fullPath: '/collection/$address'
      preLoaderRoute: typeof CollectionAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$contract/$tokenId': {
      id: '/nft/$contract/$tokenId'
      path: '/nft/$contract/$tokenId'
      fullPath: '/nft/$contract/$tokenId'
      preLoaderRoute: typeof NftContractTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  MarketplaceRoute: MarketplaceRoute,
  MyNftsRoute: MyNftsRoute,
  CollectionAddressRoute: CollectionAddressRoute,
  MintCollectionRoute: MintCollectionRoute,
  MintIndexRoute: MintIndexRoute,
  NftContractTokenIdRoute: NftContractTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
